version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/pythonApp/
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/pythonApp/scripts
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755
    setfacl:
      - "u:ubuntu:rwx"
      - "u:root:rwx"
    owner: root
    type:
      - file
    
  - object: /home/ubuntu/pythonApp
    pattern: "*.py"
    owner: ubuntu
    group: ubuntu
    mode: 755
    setfacl:
      - "u:ubuntu:rwx"
      
    owner: root
    type:
      - file

hooks:
      
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 100
      runas: root
      
  
      
